name: Daily AI News Fetch

on:
  schedule:
    # 每天两次，早上 8 点和晚上 8 点（UTC 时间）
    - cron: '0 0 * * *'
    - cron: '0 10 * * *'
  workflow_dispatch:  # 你也可以手动触发
    # 手动触发时，提供一个按钮来运行
    inputs:
      some_input:
        description: 'Trigger fetch'
        required: true
        default: 'yes'

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install feedparser notion-client

    # Step 4: Run your Python script to fetch and save AI news
    - name: Run AI News Script
      run: |
        python ai-news.py
